version: '3.5'

services:
  app:
    container_name: ENVIRONMENT-NAME-PROJECT-NAME
    image: IMAGE-NAME:IMAGE-TAG
    ports:
      - 'P-MAPPING'
    restart: unless-stopped
    pull_policy: always
    networks:
      meu-solutions-product-alpha-net:
        ipv4_address: 192.167.12.21
networks:
  meu-solutions-product-alpha-net:
    external: true
    name: meu-solutions-product-alpha-net