import type { PostContent, PostExtended } from "@/types/post";

export const mockPosts: PostExtended[] = [
  {
    id: "mock-post-001",
    title:
      "VIETPRODEV - Leading Software Development and Programming Training Provider",
    slug: "vietprodev-leading-provider",
    code: "MOCK-001",
    summary:
      "VIETPRODEV is proud to be a leading provider in software development and programming training, offering modern technology solutions and in-depth training programs based on real-world projects.",
    thumbnail_path: "/images/service-1.png",
    thumbnail_compress_info: {
      mobile: "/images/service-1.png",
      tablet: "/images/service-1.png",
      desktop: "/images/service-1.png",
      preload: "/images/service-1.png",
    },
    position: 1,
    is_hidden: false,
    is_service: false,
    view: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: "system",
    updated_by: null,
    expired_at: null,
    author: "VIETPRODEV",
    post_content: [
      {
        id: "mock-content-001-1",
        content:
          "<p>VIETPRODEV is proud to be a leading provider in software development and programming training, offering modern technology solutions and in-depth training programs based on real-world projects to meet the ever-increasing demands of the market. With the mission of driving business growth through optimized software solutions, while also training a talented generation of programmers, we are always committed to quality and creativity in every product and service.</p>",
        position: 1,
        image_columns: 1,
        image_rows: 1,
        post_id: "mock-post-001",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        created_by: "system",
        updated_by: null,
        post_content_images: [],
      },
      {
        id: "mock-content-001-2",
        content:
          "<h3>Professional Software Development Solutions</h3><ul><li>Build custom software tailored to enterprise needs with modern technology.</li><li>Develop cross-platform web, mobile, and desktop applications.</li><li>Consult on digital transformation and optimize operational processes.</li><li>Support maintenance, upgrades, and scaling of existing software systems.</li></ul>",
        position: 2,
        image_columns: 1,
        image_rows: 1,
        post_id: "mock-post-001",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        created_by: "system",
        updated_by: null,
        post_content_images: [],
      },
      {
        id: "mock-content-001-3",
        content:
          "<h3>Our Commitment</h3><p>VIETPRODEV's team of experienced experts continuously researches and applies advanced technologies, building customized solutions tailored to each client, thereby delivering sustainable value and driving long-term growth for businesses as well as the community of learners.</p>",
        position: 3,
        image_columns: 1,
        image_rows: 1,
        post_id: "mock-post-001",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        created_by: "system",
        updated_by: null,
        post_content_images: [],
      },
    ] as PostContent[],
  },
  {
    id: "mock-post-002",
    title:
      "VIETPRODEV - In-depth Programming Training Program Based on Real-world Projects",
    slug: "vietprodev-programming-training",
    code: "MOCK-002",
    summary:
      "VIETPRODEV offers an in-depth programming training program based on real-world projects, helping learners master knowledge and practical skills to be ready to work in an enterprise environment.",
    thumbnail_path: "/images/service-2.png",
    thumbnail_compress_info: {
      mobile: "/images/service-2.png",
      tablet: "/images/service-2.png",
      desktop: "/images/service-2.png",
      preload: "/images/service-2.png",
    },
    position: 2,
    is_hidden: false,
    is_service: false,
    view: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: "system",
    updated_by: null,
    expired_at: null,
    author: "VIETPRODEV",
    post_content: [
      {
        id: "mock-content-002-1",
        content:
          "<p>VIETPRODEV is proud to be a leading provider in software development and programming training, offering modern technology solutions and in-depth training programs based on real-world projects to meet the ever-increasing demands of the market. Our training programs are designed closely to real hiring needs, helping learners gain experience through real projects during the learning process.</p>",
        position: 1,
        image_columns: 1,
        image_rows: 1,
        post_id: "mock-post-002",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        created_by: "system",
        updated_by: null,
        post_content_images: [],
      },
      {
        id: "mock-content-002-2",
        content:
          "<h3>In-depth Training Curriculum</h3><ul><li>Frontend Development: HTML, CSS, JavaScript, React, Next.js, Vue.js.</li><li>Backend Development: Node.js, Python, Java, Database Design.</li><li>Mobile Development: React Native, Flutter, iOS and Android native.</li><li>DevOps & Cloud: Docker, Kubernetes, AWS, CI/CD pipeline.</li></ul>",
        position: 2,
        image_columns: 1,
        image_rows: 1,
        post_id: "mock-post-002",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        created_by: "system",
        updated_by: null,
        post_content_images: [],
      },
      {
        id: "mock-content-002-3",
        content:
          "<h3>Practical Training Method</h3><p>VIETPRODEV's team of experienced experts continuously researches and applies advanced technologies, building customized solutions tailored to each client, thereby delivering sustainable value and driving long-term growth for businesses as well as the community of learners. Each learner receives 1-on-1 mentoring and participates in real company projects.</p>",
        position: 3,
        image_columns: 1,
        image_rows: 1,
        post_id: "mock-post-002",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        created_by: "system",
        updated_by: null,
        post_content_images: [],
      },
    ] as PostContent[],
  },
  {
    id: "mock-post-003",
    title:
      "VIETPRODEV - Custom Technology Solutions for Businesses",
    slug: "vietprodev-technology-solutions",
    code: "MOCK-003",
    summary:
      "VIETPRODEV provides custom technology solutions tailored to each business, helping optimize processes and drive sustainable growth.",
    thumbnail_path: "/images/service-3.png",
    thumbnail_compress_info: {
      mobile: "/images/service-3.png",
      tablet: "/images/service-3.png",
      desktop: "/images/service-3.png",
      preload: "/images/service-3.png",
    },
    position: 3,
    is_hidden: false,
    is_service: false,
    view: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: "system",
    updated_by: null,
    expired_at: null,
    author: "VIETPRODEV",
    post_content: [
      {
        id: "mock-content-003-1",
        content:
          "<p>VIETPRODEV is proud to be a leading provider in software development and programming training, offering modern technology solutions and in-depth training programs based on real-world projects to meet the ever-increasing demands of the market. With the mission of driving business growth through optimized software solutions, while also training a talented generation of programmers, we are always committed to quality and creativity in every product and service.</p>",
        position: 1,
        image_columns: 1,
        image_rows: 1,
        post_id: "mock-post-003",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        created_by: "system",
        updated_by: null,
        post_content_images: [],
      },
      {
        id: "mock-content-003-2",
        content:
          "<h3>Custom Software Development Services</h3><ul><li>Analyze needs and consult on suitable technology solutions.</li><li>Design and develop software through a professional process.</li><li>System integration and comprehensive digital transformation.</li><li>Continuous operations support, maintenance, and upgrades.</li></ul>",
        position: 2,
        image_columns: 1,
        image_rows: 1,
        post_id: "mock-post-003",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        created_by: "system",
        updated_by: null,
        post_content_images: [],
      },
      {
        id: "mock-content-003-3",
        content:
          "<h3>VIETPRODEV's Team of Experts</h3><p>VIETPRODEV's team of experienced experts continuously researches and applies advanced technologies, building customized solutions tailored to each client, thereby delivering sustainable value and driving long-term growth for businesses as well as the community of learners.</p>",
        position: 3,
        image_columns: 1,
        image_rows: 1,
        post_id: "mock-post-003",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        created_by: "system",
        updated_by: null,
        post_content_images: [],
      },
    ] as PostContent[],
  },
  // {
  //   id: "mock-post-002",
  //   title: "Sample Post 2 - Key Features",
  //   slug: "sample-post-2-key-features",
  //   code: "MOCK-002",
  //   summary:
  //     "Explore the key features of the system: multimedia content management, automatic SEO, responsive design and more.",
  //   thumbnail_path: "/images/service-2.png",
  //   thumbnail_compress_info: {
  //     mobile: "/images/service-2.png",
  //     tablet: "/images/service-2.png",
  //     desktop: "/images/service-2.png",
  //     preload: "/images/service-2.png",
  //   },
  //   position: 2,
  //   is_hidden: false,
  //   is_service: false,
  //   view: 0,
  //   created_at: new Date().toISOString(),
  //   updated_at: new Date().toISOString(),
  //   created_by: "system",
  //   updated_by: null,
  //   expired_at: null,
  //   author: "System",
  //   post_content: [
  //     {
  //       id: "mock-content-002-1",
  //       content:
  //         "The system is designed with a user-friendly interface, easy to use even for beginners. All operations are optimized to minimize working time.",
  //       position: 1,
  //       image_columns: 1,
  //       image_rows: 1,
  //       post_id: "mock-post-002",
  //       created_at: new Date().toISOString(),
  //       updated_at: new Date().toISOString(),
  //       created_by: "system",
  //       updated_by: null,
  //       post_content_images: [],
  //     },
  //     {
  //       id: "mock-content-002-2",
  //       content:
  //         "The smart search feature helps you quickly find the content you need. The system also supports filtering and sorting by various criteria.",
  //       position: 2,
  //       image_columns: 1,
  //       image_rows: 1,
  //       post_id: "mock-post-002",
  //       created_at: new Date().toISOString(),
  //       updated_at: new Date().toISOString(),
  //       created_by: "system",
  //       updated_by: null,
  //       post_content_images: [],
  //     },
  //   ] as PostContent[],
  // },
  // {
  //   id: "mock-post-003",
  //   title: "Sample Post 3 - Frequently Asked Questions",
  //   slug: "sample-post-3-frequently-asked-questions",
  //   code: "MOCK-003",
  //   summary:
  //     "A collection of frequently asked questions and detailed guides to help you resolve issues quickly. Contact support if you need further assistance.",
  //   thumbnail_path: "/images/service-3.png",
  //   thumbnail_compress_info: {
  //     mobile: "/images/service-3.png",
  //     tablet: "/images/service-3.png",
  //     desktop: "/images/service-3.png",
  //     preload: "/images/service-3.png",
  //   },
  //   position: 3,
  //   is_hidden: false,
  //   is_service: false,
  //   view: 0,
  //   created_at: new Date().toISOString(),
  //   updated_at: new Date().toISOString(),
  //   created_by: "system",
  //   updated_by: null,
  //   expired_at: null,
  //   author: "System",
  //   post_content: [
  //     {
  //       id: "mock-content-003-1",
  //       content:
  //         "How to create a new post? - Go to the admin section, select a category and click the 'Create New Post' button. Fill in all the information and save.",
  //       position: 1,
  //       image_columns: 1,
  //       image_rows: 1,
  //       post_id: "mock-post-003",
  //       created_at: new Date().toISOString(),
  //       updated_at: new Date().toISOString(),
  //       created_by: "system",
  //       updated_by: null,
  //       post_content_images: [],
  //     },
  //     {
  //       id: "mock-content-003-2",
  //       content:
  //         "If you encounter technical issues, please contact support via email or hotline. We will respond within 24 business hours.",
  //       position: 2,
  //       image_columns: 1,
  //       image_rows: 1,
  //       post_id: "mock-post-003",
  //       created_at: new Date().toISOString(),
  //       updated_at: new Date().toISOString(),
  //       created_by: "system",
  //       updated_by: null,
  //       post_content_images: [],
  //     },
  //   ] as PostContent[],
  // },
];

export function getMockPostsForCategory(
  categoryId: string,
  categoryName: string,
  categoryLink: string,
): PostExtended[] {
  return mockPosts.map((post) => ({
    ...post,
    category: {
      id: categoryId,
      name: categoryName,
      link: categoryLink,
    },
  }));
}

export function getMockPostBySlug(slug: string): PostExtended | undefined {
  return mockPosts.find((post) => post.slug === slug);
}
