import type { PostContent, PostExtended } from "@/types/post";

export const mockPosts: PostExtended[] = [
  {
    id: "mock-post-001",
    title:
      "VIETPRODEV - Đơn vị hàng đầu trong phát triển phần mềm và đào tạo lập trình",
    slug: "vietprodev-don-vi-hang-dau",
    code: "MOCK-001",
    summary:
      "VIETPRODEV tự hào là đơn vị hàng đầu trong lĩnh vực phát triển phần mềm và đào tạo lập trình, mang đến những giải pháp công nghệ hiện đại và chương trình đào tạo chuyên sâu theo dự án thực tế.",
    thumbnail_path: "/images/service-1.png",
    thumbnail_compress_info: {
      mobile: "/images/service-1.png",
      tablet: "/images/service-1.png",
      desktop: "/images/service-1.png",
      preload: "/images/service-1.png",
    },
    position: 1,
    is_hidden: false,
    is_service: false,
    view: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: "system",
    updated_by: null,
    expired_at: null,
    author: "VIETPRODEV",
    post_content: [
      {
        id: "mock-content-001-1",
        content:
          "<p>VIETPRODEV tự hào là đơn vị hàng đầu trong lĩnh vực phát triển phần mềm và đào tạo lập trình, mang đến những giải pháp công nghệ hiện đại và chương trình đào tạo chuyên sâu theo dự án thực tế nhằm đáp ứng nhu cầu ngày càng cao của thị trường. Với sứ mệnh thúc đẩy sự phát triển của doanh nghiệp thông qua các giải pháp phần mềm tối ưu, đồng thời đào tạo ra thế hệ lập trình viên tài năng, chúng tôi luôn cam kết chất lượng và sáng tạo trong từng sản phẩm và dịch vụ.</p>",
        position: 1,
        image_columns: 1,
        image_rows: 1,
        post_id: "mock-post-001",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        created_by: "system",
        updated_by: null,
        post_content_images: [],
      },
      {
        id: "mock-content-001-2",
        content:
          "<h3>Giải pháp phát triển phần mềm chuyên nghiệp</h3><ul><li>Xây dựng phần mềm tùy chỉnh theo yêu cầu doanh nghiệp với công nghệ hiện đại.</li><li>Phát triển ứng dụng web, mobile và desktop đa nền tảng.</li><li>Tư vấn chuyển đổi số và tối ưu hóa quy trình vận hành.</li><li>Hỗ trợ bảo trì, nâng cấp và mở rộng hệ thống phần mềm hiện có.</li></ul>",
        position: 2,
        image_columns: 1,
        image_rows: 1,
        post_id: "mock-post-001",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        created_by: "system",
        updated_by: null,
        post_content_images: [],
      },
      {
        id: "mock-content-001-3",
        content:
          "<h3>Cam kết của chúng tôi</h3><p>Đội ngũ chuyên gia giàu kinh nghiệm của VIETPRODEV không ngừng nghiên cứu, ứng dụng các công nghệ tiên tiến và xây dựng các giải pháp tùy chỉnh phù hợp với từng khách hàng, từ đó mang lại giá trị bền vững và thúc đẩy sự phát triển lâu dài cho doanh nghiệp cũng như cộng đồng học viên.</p>",
        position: 3,
        image_columns: 1,
        image_rows: 1,
        post_id: "mock-post-001",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        created_by: "system",
        updated_by: null,
        post_content_images: [],
      },
    ] as PostContent[],
  },
  {
    id: "mock-post-002",
    title:
      "VIETPRODEV - Chương trình đào tạo lập trình viên chuyên sâu theo dự án thực tế",
    slug: "vietprodev-dao-tao-lap-trinh",
    code: "MOCK-002",
    summary:
      "VIETPRODEV cung cấp chương trình đào tạo lập trình viên chuyên sâu theo dự án thực tế, giúp học viên nắm vững kiến thức và kỹ năng thực tiễn để sẵn sàng làm việc trong môi trường doanh nghiệp.",
    thumbnail_path: "/images/service-2.png",
    thumbnail_compress_info: {
      mobile: "/images/service-2.png",
      tablet: "/images/service-2.png",
      desktop: "/images/service-2.png",
      preload: "/images/service-2.png",
    },
    position: 2,
    is_hidden: false,
    is_service: false,
    view: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: "system",
    updated_by: null,
    expired_at: null,
    author: "VIETPRODEV",
    post_content: [
      {
        id: "mock-content-002-1",
        content:
          "<p>VIETPRODEV tự hào là đơn vị hàng đầu trong lĩnh vực phát triển phần mềm và đào tạo lập trình, mang đến những giải pháp công nghệ hiện đại và chương trình đào tạo chuyên sâu theo dự án thực tế nhằm đáp ứng nhu cầu ngày càng cao của thị trường. Chương trình đào tạo của chúng tôi được thiết kế bám sát nhu cầu tuyển dụng thực tế, giúp học viên tích lũy kinh nghiệm qua các dự án thực tế ngay trong quá trình học.</p>",
        position: 1,
        image_columns: 1,
        image_rows: 1,
        post_id: "mock-post-002",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        created_by: "system",
        updated_by: null,
        post_content_images: [],
      },
      {
        id: "mock-content-002-2",
        content:
          "<h3>Lộ trình đào tạo chuyên sâu</h3><ul><li>Frontend Development: HTML, CSS, JavaScript, React, Next.js, Vue.js.</li><li>Backend Development: Node.js, Python, Java, Database Design.</li><li>Mobile Development: React Native, Flutter, iOS và Android native.</li><li>DevOps & Cloud: Docker, Kubernetes, AWS, CI/CD pipeline.</li></ul>",
        position: 2,
        image_columns: 1,
        image_rows: 1,
        post_id: "mock-post-002",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        created_by: "system",
        updated_by: null,
        post_content_images: [],
      },
      {
        id: "mock-content-002-3",
        content:
          "<h3>Phương pháp đào tạo thực chiến</h3><p>Đội ngũ chuyên gia giàu kinh nghiệm của VIETPRODEV không ngừng nghiên cứu, ứng dụng các công nghệ tiên tiến và xây dựng các giải pháp tùy chỉnh phù hợp với từng khách hàng, từ đó mang lại giá trị bền vững và thúc đẩy sự phát triển lâu dài cho doanh nghiệp cũng như cộng đồng học viên. Mỗi học viên đều được mentor 1-1 và tham gia vào các dự án thực tế của công ty.</p>",
        position: 3,
        image_columns: 1,
        image_rows: 1,
        post_id: "mock-post-002",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        created_by: "system",
        updated_by: null,
        post_content_images: [],
      },
    ] as PostContent[],
  },
  {
    id: "mock-post-003",
    title:
      "VIETPRODEV - Giải pháp công nghệ tùy chỉnh cho doanh nghiệp",
    slug: "vietprodev-giai-phap-cong-nghe",
    code: "MOCK-003",
    summary:
      "VIETPRODEV mang đến giải pháp công nghệ tùy chỉnh phù hợp với từng doanh nghiệp, giúp tối ưu hóa quy trình và thúc đẩy tăng trưởng bền vững.",
    thumbnail_path: "/images/service-3.png",
    thumbnail_compress_info: {
      mobile: "/images/service-3.png",
      tablet: "/images/service-3.png",
      desktop: "/images/service-3.png",
      preload: "/images/service-3.png",
    },
    position: 3,
    is_hidden: false,
    is_service: false,
    view: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: "system",
    updated_by: null,
    expired_at: null,
    author: "VIETPRODEV",
    post_content: [
      {
        id: "mock-content-003-1",
        content:
          "<p>VIETPRODEV tự hào là đơn vị hàng đầu trong lĩnh vực phát triển phần mềm và đào tạo lập trình, mang đến những giải pháp công nghệ hiện đại và chương trình đào tạo chuyên sâu theo dự án thực tế nhằm đáp ứng nhu cầu ngày càng cao của thị trường. Với sứ mệnh thúc đẩy sự phát triển của doanh nghiệp thông qua các giải pháp phần mềm tối ưu, đồng thời đào tạo ra thế hệ lập trình viên tài năng, chúng tôi luôn cam kết chất lượng và sáng tạo trong từng sản phẩm và dịch vụ.</p>",
        position: 1,
        image_columns: 1,
        image_rows: 1,
        post_id: "mock-post-003",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        created_by: "system",
        updated_by: null,
        post_content_images: [],
      },
      {
        id: "mock-content-003-2",
        content:
          "<h3>Dịch vụ phát triển phần mềm tùy chỉnh</h3><ul><li>Phân tích nhu cầu và tư vấn giải pháp công nghệ phù hợp.</li><li>Thiết kế và phát triển phần mềm theo quy trình chuyên nghiệp.</li><li>Tích hợp hệ thống và chuyển đổi số toàn diện.</li><li>Hỗ trợ vận hành, bảo trì và nâng cấp liên tục.</li></ul>",
        position: 2,
        image_columns: 1,
        image_rows: 1,
        post_id: "mock-post-003",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        created_by: "system",
        updated_by: null,
        post_content_images: [],
      },
      {
        id: "mock-content-003-3",
        content:
          "<h3>Đội ngũ chuyên gia của VIETPRODEV</h3><p>Đội ngũ chuyên gia giàu kinh nghiệm của VIETPRODEV không ngừng nghiên cứu, ứng dụng các công nghệ tiên tiến và xây dựng các giải pháp tùy chỉnh phù hợp với từng khách hàng, từ đó mang lại giá trị bền vững và thúc đẩy sự phát triển lâu dài cho doanh nghiệp cũng như cộng đồng học viên.</p>",
        position: 3,
        image_columns: 1,
        image_rows: 1,
        post_id: "mock-post-003",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        created_by: "system",
        updated_by: null,
        post_content_images: [],
      },
    ] as PostContent[],
  },
  // {
  //   id: "mock-post-002",
  //   title: "Bài viết mẫu 2 - Các tính năng nổi bật",
  //   slug: "bai-viet-mau-2-cac-tinh-nang-noi-bat",
  //   code: "MOCK-002",
  //   summary:
  //     "Khám phá các tính năng nổi bật của hệ thống: quản lý nội dung đa phương tiện, SEO tự động, responsive design và nhiều hơn nữa.",
  //   thumbnail_path: "/images/service-2.png",
  //   thumbnail_compress_info: {
  //     mobile: "/images/service-2.png",
  //     tablet: "/images/service-2.png",
  //     desktop: "/images/service-2.png",
  //     preload: "/images/service-2.png",
  //   },
  //   position: 2,
  //   is_hidden: false,
  //   is_service: false,
  //   view: 0,
  //   created_at: new Date().toISOString(),
  //   updated_at: new Date().toISOString(),
  //   created_by: "system",
  //   updated_by: null,
  //   expired_at: null,
  //   author: "Hệ thống",
  //   post_content: [
  //     {
  //       id: "mock-content-002-1",
  //       content:
  //         "Hệ thống được thiết kế với giao diện thân thiện, dễ sử dụng ngay cả với người mới bắt đầu. Tất cả các thao tác đều được tối ưu hóa để giảm thiểu thời gian làm việc.",
  //       position: 1,
  //       image_columns: 1,
  //       image_rows: 1,
  //       post_id: "mock-post-002",
  //       created_at: new Date().toISOString(),
  //       updated_at: new Date().toISOString(),
  //       created_by: "system",
  //       updated_by: null,
  //       post_content_images: [],
  //     },
  //     {
  //       id: "mock-content-002-2",
  //       content:
  //         "Tính năng tìm kiếm thông minh giúp bạn nhanh chóng tìm thấy nội dung cần thiết. Hệ thống cũng hỗ trợ lọc và sắp xếp theo nhiều tiêu chí khác nhau.",
  //       position: 2,
  //       image_columns: 1,
  //       image_rows: 1,
  //       post_id: "mock-post-002",
  //       created_at: new Date().toISOString(),
  //       updated_at: new Date().toISOString(),
  //       created_by: "system",
  //       updated_by: null,
  //       post_content_images: [],
  //     },
  //   ] as PostContent[],
  // },
  // {
  //   id: "mock-post-003",
  //   title: "Bài viết mẫu 3 - Hỏi đáp thường gặp",
  //   slug: "bai-viet-mau-3-hoi-dap-thuong-gap",
  //   code: "MOCK-003",
  //   summary:
  //     "Tổng hợp các câu hỏi thường gặp và hướng dẫn chi tiết giúp bạn giải quyết vấn đề nhanh chóng. Liên hệ với bộ phận hỗ trợ nếu cần thêm trợ giúp.",
  //   thumbnail_path: "/images/service-3.png",
  //   thumbnail_compress_info: {
  //     mobile: "/images/service-3.png",
  //     tablet: "/images/service-3.png",
  //     desktop: "/images/service-3.png",
  //     preload: "/images/service-3.png",
  //   },
  //   position: 3,
  //   is_hidden: false,
  //   is_service: false,
  //   view: 0,
  //   created_at: new Date().toISOString(),
  //   updated_at: new Date().toISOString(),
  //   created_by: "system",
  //   updated_by: null,
  //   expired_at: null,
  //   author: "Hệ thống",
  //   post_content: [
  //     {
  //       id: "mock-content-003-1",
  //       content:
  //         "Làm thế nào để tạo bài viết mới? - Truy cập vào phần quản trị, chọn danh mục và nhấn nút 'Tạo bài viết mới'. Điền đầy đủ thông tin và lưu lại.",
  //       position: 1,
  //       image_columns: 1,
  //       image_rows: 1,
  //       post_id: "mock-post-003",
  //       created_at: new Date().toISOString(),
  //       updated_at: new Date().toISOString(),
  //       created_by: "system",
  //       updated_by: null,
  //       post_content_images: [],
  //     },
  //     {
  //       id: "mock-content-003-2",
  //       content:
  //         "Nếu gặp vấn đề kỹ thuật, vui lòng liên hệ với bộ phận hỗ trợ qua email hoặc hotline. Chúng tôi sẽ phản hồi trong vòng 24 giờ làm việc.",
  //       position: 2,
  //       image_columns: 1,
  //       image_rows: 1,
  //       post_id: "mock-post-003",
  //       created_at: new Date().toISOString(),
  //       updated_at: new Date().toISOString(),
  //       created_by: "system",
  //       updated_by: null,
  //       post_content_images: [],
  //     },
  //   ] as PostContent[],
  // },
];

export function getMockPostsForCategory(
  categoryId: string,
  categoryName: string,
  categoryLink: string,
): PostExtended[] {
  return mockPosts.map((post) => ({
    ...post,
    category: {
      id: categoryId,
      name: categoryName,
      link: categoryLink,
    },
  }));
}

export function getMockPostBySlug(slug: string): PostExtended | undefined {
  return mockPosts.find((post) => post.slug === slug);
}
